In [3]:
import pandas as pd

In [10]:
data = pd.read_csv('./fama.txt', header = None, sep = " ", error_bad_lines=False)

b'Skipping line 6: expected 7 fields, saw 8\nSkipping line 7: expected 7 fields, saw 8\nSkipping line 8: expected 7 fields, saw 8\nSkipping line 9: expected 7 fields, saw 8\nSkipping line 10: expected 7 fields, saw 8\nSkipping line 11: expected 7 fields, saw 8\nSkipping line 21: expected 7 fields, saw 8\nSkipping line 31: expected 7 fields, saw 8\nSkipping line 32: expected 7 fields, saw 8\nSkipping line 34: expected 7 fields, saw 8\nSkipping line 47: expected 7 fields, saw 8\nSkipping line 62: expected 7 fields, saw 8\nSkipping line 68: expected 7 fields, saw 8\nSkipping line 69: expected 7 fields, saw 8\nSkipping line 70: expected 7 fields, saw 8\nSkipping line 89: expected 7 fields, saw 8\nSkipping line 91: expected 7 fields, saw 8\nSkipping line 100: expected 7 fields, saw 8\nSkipping line 101: expected 7 fields, saw 8\nSkipping line 146: expected 7 fields, saw 8\nSkipping line 149: expected 7 fields, saw 8\nSkipping line 161: expected 7 fields, saw 8\nSkipping line 164: expected 7 fields, saw 8\nSkipping line 172: expected 7 fields, saw 8\nSkipping line 173: expected 7 fields, saw 8\nSkipping line 174: expected 7 fields, saw 8\nSkipping line 175: expected 7 fields, saw 8\nSkipping line 202: expected 7 fields, saw 8\nSkipping line 212: expected 7 fields, saw 8\nSkipping line 213: expected 7 fields, saw 8\nSkipping line 214: expected 7 fields, saw 8\nSkipping line 215: expected 7 fields, saw 8\nSkipping line 216: expected 7 fields, saw 8\nSkipping line 217: expected 7 fields, saw 8\nSkipping line 218: expected 7 fields, saw 8\nSkipping line 219: expected 7 fields, saw 8\nSkipping line 220: expected 7 fields, saw 8\nSkipping line 232: expected 7 fields, saw 8\nSkipping line 233: expected 7 fields, saw 8\nSkipping line 234: expected 7 fields, saw 8\nSkipping line 235: expected 7 fields, saw 8\nSkipping line 251: expected 7 fields, saw 8\nSkipping line 252: expected 7 fields, saw 8\nSkipping line 253: expected 7 fields, saw 8\n'

In [11]:
data

,0,1,2,3,4,5,6
0,2016-11-08,14:31:00+00:00,NaN,0.990474,-1.941435,NaN,0.424430
1,2016-11-09,14:31:00+00:00,NaN,2.083929,-1.722483,NaN,0.292394
2,2016-11-10,14:31:00+00:00,NaN,3.615208,-0.323271,-0.293212,NaN
3,2016-11-11,14:31:00+00:00,NaN,4.004412,NaN,0.592384,-0.264628
4,2016-11-14,14:31:00+00:00,NaN,1.581417,NaN,2.798087,-0.167658
5,2016-11-23,14:31:00+00:00,NaN,1.188400,-0.051578,NaN,0.047821
6,2016-11-25,14:31:00+00:00,NaN,0.812971,NaN,0.173479,-0.370590
7,2016-11-28,14:31:00+00:00,NaN,1.382088,-0.005996,-0.753483,NaN
8,2016-11-29,14:31:00+00:00,NaN,0.190814,NaN,0.451570,-0.413820
9,2016-11-30,14:31:00+00:00,NaN,0.163243,NaN,0.083141,-0.283796
10,2016-12-01,14:31:00+00:00,-0.181217,-0.420576,NaN,1.258896,NaN
11,2016-12-02,14:31:00+00:00,-0.902812,-0.475199,NaN,2.314211,NaN
12,2016-12-05,14:31:00+00:00,-0.389970,-0.770747,NaN,2.042421,NaN
13,2016-12-06,14:31:00+00:00,NaN,0.022636,-0.033106,NaN,1.825396
14,2016-12-08,14:31:00+00:00,NaN,2.295814,-0.202920,NaN,0.201092
15,2016-12-09,14:31:00+00:00,NaN,2.485547,NaN,0.747962,-0.851529
16,2016-12-12,14:31:00+00:00,NaN,2.511994,NaN,0.846714,-0.670983
17,2016-12-13,14:31:00+00:00,NaN,2.043394,NaN,0.031873,-0.075158
18,2016-12-14,14:31:00+00:00,NaN,1.402681,NaN,0.242220,-0.025117
19,2016-12-15,14:31:00+00:00,NaN,0.346466,-0.282887,NaN,0.536592
20,2016-12-16,14:31:00+00:00,NaN,0.145702,-0.388940,NaN,0.041526
21,2016-12-19,14:31:00+00:00,NaN,0.077999,NaN,0.132582,-0.151636
22,2016-12-20,14:31:00+00:00,-0.391278,NaN,0.249067,NaN,0.121740
23,2016-12-23,14:31:00+00:00,NaN,0.146621,-0.222989,NaN,0.566723
24,2016-12-28,14:31:00+00:00,-0.057428,NaN,0.237078,-0.022300,NaN
25,2016-12-29,14:31:00+00:00,-0.611160,NaN,0.329636,NaN,0.205467
26,2016-12-30,14:31:00+00:00,-0.461402,-0.182287,NaN,0.030671,NaN
27,2017-01-03,14:31:00+00:00,-0.948203,-0.305441,NaN,0.684904,NaN
28,2017-01-04,14:31:00+00:00,-0.472949,NaN,0.175768,NaN,0.497936
29,2017-01-05,14:31:00+00:00,NaN,0.935745,NaN,0.637251,-0.272231
...,...,...,...,...,...,...,...
193,2017-10-09,13:31:00+00:00,NaN,0.840336,NaN,0.703786,-0.184662
194,2017-10-16,13:31:00+00:00,NaN,0.381965,-0.712740,NaN,1.285797
195,2017-10-17,13:31:00+00:00,NaN,0.274941,-1.378421,NaN,1.777829
196,2017-10-18,13:31:00+00:00,NaN,0.180392,-1.672811,NaN,1.688622
197,2017-10-19,13:31:00+00:00,NaN,0.428106,-1.396016,NaN,1.390704
198,2017-10-20,13:31:00+00:00,NaN,0.353052,-1.049328,NaN,0.830872
199,2017-10-23,13:31:00+00:00,NaN,0.700744,-0.704136,-0.098378,NaN
200,2017-10-24,13:31:00+00:00,NaN,0.266186,-0.692637,-0.018906,NaN
201,2017-10-25,13:31:00+00:00,NaN,0.332421,-0.758737,NaN,0.270848
202,2017-10-26,13:31:00+00:00,-0.203268,-0.370971,NaN,0.232740,NaN
203,2017-10-27,13:31:00+00:00,-0.586956,-0.764913,NaN,0.454761,NaN
204,2017-10-30,13:31:00+00:00,NaN,0.605138,-0.762323,NaN,0.477442
205,2017-10-31,13:31:00+00:00,NaN,0.097447,-0.681568,NaN,0.640235
206,2017-11-01,13:31:00+00:00,NaN,0.708970,-0.773053,NaN,0.256850
207,2017-11-02,13:31:00+00:00,NaN,0.755145,-0.749981,NaN,1.146593
208,2017-11-03,13:31:00+00:00,-0.031045,-0.344456,NaN,1.139388,NaN
209,2017-11-09,14:31:00+00:00,NaN,0.586157,-0.221036,NaN,0.504550
210,2017-11-10,14:31:00+00:00,-0.092865,NaN,0.124976,NaN,0.973118
211,2017-11-13,14:31:00+00:00,-0.286299,NaN,0.638137,NaN,0.868298
212,2017-11-14,14:31:00+00:00,-0.131823,NaN,0.665660,NaN,0.424237
213,2017-11-15,14:31:00+00:00,-0.532572,NaN,0.472740,NaN,0.243015
214,2017-11-16,14:31:00+00:00,-0.685515,NaN,0.036479,NaN,0.069833
215,2017-11-17,14:31:00+00:00,NaN,0.205751,NaN,0.313472,-0.644721
216,2017-11-20,14:31:00+00:00,-0.177674,NaN,0.705601,-0.538579,NaN
217,2017-11-21,14:31:00+00:00,NaN,0.213393,NaN,1.376374,-0.244889
218,2017-11-22,14:31:00+00:00,NaN,1.376204,NaN,1.170715,-0.607194
219,2017-11-24,14:31:00+00:00,NaN,0.448165,NaN,0.887327,-0.104468
220,2017-11-27,14:31:00+00:00,NaN,0.957810,NaN,1.075480,-1.137076
221,2017-11-28,14:31:00+00:00,NaN,0.762709,NaN,0.910173,-1.026275
222,2017-11-29,14:31:00+00:00,NaN,1.112098,NaN,0.294525,-0.862914